ðŸ¦œ Uncomment the following code for the [TidyTuesday Bird Bath dataset](https://github.com/rfordatascience/tidytuesday/tree/master/data/2021/2021-08-31).ðŸ¦‰

In [1]:
library('tidyverse')

â”€â”€ Attaching packages â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ tidyverse 1.3.1 â”€â”€

âœ” ggplot2 3.3.5     âœ” purrr   0.3.4
âœ” tibble  3.1.3     âœ” dplyr   1.0.7
âœ” tidyr   1.1.3     âœ” stringr 1.4.0
âœ” readr   1.4.0     âœ” forcats 0.5.1

â”€â”€ Conflicts â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ tidyverse_conflicts() â”€â”€
âœ– dplyr::filter() masks stats::filter()
âœ– dplyr::lag()    masks stats::lag()

In [21]:
df_birdbath = read_csv(
    'https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-08-31/bird_baths.csv?raw=true',
    col_types = cols()
)

df_birdbath %>% as_tibble

       survey_year urban_rural bioregions
1      2014        Urban       South Eastern Queensland
2      2014        Urban       South Eastern Queensland
3      2014        Urban       South Eastern Queensland
4      2014        Urban       South Eastern Queensland
5      2014        Urban       South Eastern Queensland
6      2014        Urban       South Eastern Queensland
7      2014        Urban       South Eastern Queensland
8      2014        Urban       South Eastern Queensland
9      2014        Urban       South Eastern Queensland
10     2014        Urban       South Eastern Queensland
11     2014        Urban       South Eastern Queensland
12     2014        Urban       South Eastern Queensland
13     2014        Urban       South Eastern Queensland
14     2014        Urban       South Eastern Queensland
15     2014        Urban       South Eastern Queensland
16     2014        Urban       South Eastern Queensland
17     2014        Urban       South Eastern Queensland
18     2014        Urban       South Eastern Queensland
19     2014        Urban       South Eastern Queensland
20     2014        Urban       South Eastern Queensland
21     2014        Urban       South Eastern Queensland
22     2014        Urban       South Eastern Queensland
23     2014        Urban       South Eastern Queensland
24     2014        Urban       South Eastern Queensland
25     2014        Urban       South Eastern Queensland
26     2014        Urban       South Eastern Queensland
27     2014        Urban       South Eastern Queensland
28     2014        Urban       South Eastern Queensland
29     2014        Urban       South Eastern Queensland
30     2014        Urban       South Eastern Queensland
â‹®      â‹®           â‹®           â‹®
161028 NA          NA          NA
161029 NA          NA          NA
161030 NA          NA          NA
161031 NA          NA          NA
161032 NA          NA          NA
161033 NA          NA          NA
161034 NA          NA          NA
161035 NA          NA          NA
161036 NA          NA          NA
161037 NA          NA          NA
161038 NA          NA          NA
161039 NA          NA          NA
161040 NA          NA          NA
161041 NA          NA          NA
161042 NA          NA          NA
161043 NA          NA          NA
161044 NA          NA          NA
161045 NA          NA          NA
161046 NA          NA          NA
161047 NA          NA          NA
161048 NA          NA          NA
161049 NA          NA          NA
161050 NA          NA          NA
161051 NA          NA          NA
161052 NA          NA          NA
161053 NA          NA          NA
161054 NA          NA          NA
161055 NA          NA          NA
161056 NA          NA          NA
161057 NA          NA          NA
       bird_type                  bird_count
1      Bassian Thrush             0
2      Chestnut-breasted Mannikin 0
3      Wild Duck                  0
4      Willie Wagtail             0
5      Regent Bowerbird           0
6      Rufous Fantail             0
7      Spiny-cheeked Honeyeater   0
8      Flame Robin                0
9      European Goldfinch         0
10     Noisy Friarbird            0
11     Sulphur-crested Cockatoo   0
12     Scaly-breasted Lorikeet    0
13     Tete                       0
14     Double-barred Finch        0
15     Buff-rumped Thornbill      0
16     Purple Swamphen            0
17     Green Catbird              0
18     Rufous Whistler            0
19     Southern Whiteface         0
20     Musk Lorikeet              0
21     Red-capped Robin           0
22     Gang-gang Cockatoo         0
23     Satin Bowerbird            0
24     Grey Currawong             0
25     Eastern Spinebill          0
26     Laughing Kookaburra        0
27     Little Wattlebird          0
28     Restless Flycatcher        0
29     Buff-banded Rail           0
30     Red-backed Fairy-wren      0
â‹®      â‹®                          â‹®
161028 Australian Brush-turkey     10
161029 Black Butcherbird            1
161030 Rose Robin                   4
161031 Pale-yellow Robin            1
161032 Scarlet Honeyeater           8
161033 Eastern Rosella             79
161034 Yellow-tufted Honeyeater     3
161035 Torresian Crow              22
161036 Grey Shrike-thrush          52
161037 Forest Raven                 1
161038 Silvereye                   80
161039 Little Shrike-thrush         1
161040 Brown Treecreeper            8
161041 Noisy Miner                292
161042 Superb Lyrebird              1
161043 Brown Cuckoo-dove           17
161044 Common Bronzewing           34
161045 White-naped Honeyeater      23
161046 Brown Honeyeater            60
161047 Spotted Dove               151
161048 Rockwarbler                  2
161049 Masked Lapwing               3
161050 Yellow-rumped Thornbill     18
161051 Hooded Robin                 1
161052 Wonga Pigeon                12
161053 White-winged Chough          8
161054 Eastern Whipbird            21
161055 Golden Whistler             19
161056 Satin Flycatcher             1
161057 Grey Fantail               123

Each row represents the number of times a type of bird was observed at a bird bath in the survey year.

We want to just work with the most numerous birds for baths that have been categorized as "Urban" or "Rural."

Find the top fifteen bird types by total `bird_count` after filtering out baths where `urban_rural` category is not provided. Capture this vector with a variable called `top15_bird_types`. 

Hint: remember `pull` and `slice_max`

In [25]:
#df_birdbath %>% pull(bird_type) %>% n_distinct() tells you how many distinct bird types there are

top15_bird_types <-
    df_birdbath %>%
    filter(!is.na(urban_rural)) %>% 
    group_by(bird_type)%>%
    summarize(total_bird_count = sum(bird_count))%>%
    slice_max(total_bird_count, n = 15)%>%
    pull(bird_type)

#top15_bird_types

1. Create a table of just the top birds using the vector above to filter. Exclude rows with `NA` vlues for `urban_rural`.
1. Group by `bird_type` and `urban_rural` and find the mean `bird_count` for each group.
1. Sort the factor levels for `bird_type` by `mean_bird_count` value at `Rural` baths.
1. Capture the output of these operations under a new variable.

Your final table will have three columns: 1) `bird-type`, 2) `urban_rural` and 3) `mean_bird_count`

In [34]:
df_mean_bird_count =
    df_birdbath %>%
    filter(!is.na(urban_rural), bird_type %in% top15_bird_types) %>% 
    group_by(bird_type, urban_rural)%>%
    summarize(mean_bird_count = mean(bird_count), .groups = 'drop') %>%
    arrange(urban_rural, mean_bird_count) %>%
    mutate(bird_type = fct_inorder(bird_type))
df_mean_bird_count

   bird_type          urban_rural mean_bird_count
1  Spotted Dove       Rural       0.03741497
2  Crested Pigeon     Rural       0.09523810
3  Pied Currawong     Rural       0.10884354
4  Magpie-lark        Rural       0.11224490
5  Red Wattlebird     Rural       0.11904762
6  Rainbow Lorikeet   Rural       0.13605442
7  Satin Bowerbird    Rural       0.14285714
8  Noisy Miner        Rural       0.20068027
9  Crimson Rosella    Rural       0.22448980
10 Australian Magpie  Rural       0.25850340
11 Red-browed Finch   Rural       0.26190476
12 Grey Fantail       Rural       0.28231293
13 Lewin's Honeyeater Rural       0.28231293
14 Eastern Spinebill  Rural       0.29591837
15 Superb Fairy-wren  Rural       0.36394558
16 Grey Fantail       Urban       0.06079027
17 Red-browed Finch   Urban       0.06079027
18 Lewin's Honeyeater Urban       0.07598784
19 Superb Fairy-wren  Urban       0.09574468
20 Eastern Spinebill  Urban       0.10030395
21 Crimson Rosella    Urban       0.13525836
22 Satin Bowerbird    Urban       0.13525836
23 Crested Pigeon     Urban       0.14741641
24 Pied Currawong     Urban       0.18996960
25 Magpie-lark        Urban       0.19300912
26 Red Wattlebird     Urban       0.20668693
27 Spotted Dove       Urban       0.21276596
28 Australian Magpie  Urban       0.28267477
29 Rainbow Lorikeet   Urban       0.29635258
30 Noisy Miner        Urban       0.35410334

Make a "Urban"/"Rural" [Cleveland dot chart](https://uc-r.github.io/public/images/visual/cleveland-dotplots/unnamed-chunk-10-1.png) following figure with your new table.

If we want to add "segments" to our dot chart, we need to re-shape our data into "wide" format. Specifically we want to have "Urban" and "Rural" as **columns** instead of **values**.

Use `pivot_wider` to make this wide table, capture it, and use `geom_segment` in combination with your wide table to add segments to your Cleveland dot chart from above ðŸ‘†.

In [35]:
wide = df_mean_bird_count %>%
    pivot_wider(id_cols = c(urban_rural), names_from = bird_type, values_from = mean_bird_count)
wide

p = ggplot(df_mean_bird_count, aes(x = mean_bird_count, y = bird_type, color = urban_rural))

p = p + geom_point()

p = p + geom_segment(x = rural, y = urban)

p

  urban_rural Spotted Dove Crested Pigeon Pied Currawong Magpie-lark
1 Rural       0.03741497   0.0952381      0.1088435      0.1122449
2 Urban       0.21276596   0.1474164      0.1899696      0.1930091
  Red Wattlebird Rainbow Lorikeet Satin Bowerbird Noisy Miner Crimson Rosella
1 0.1190476      0.1360544        0.1428571       0.2006803   0.2244898
2 0.2066869      0.2963526        0.1352584       0.3541033   0.1352584
  Australian Magpie Red-browed Finch Grey Fantail Lewin's Honeyeater
1 0.2585034         0.26190476       0.28231293   0.28231293
2 0.2826748         0.06079027       0.06079027   0.07598784
  Eastern Spinebill Superb Fairy-wren
1 0.2959184         0.36394558
2 0.1003040         0.09574468

ERROR: Error in layer(data = data, mapping = mapping, stat = stat, geom = GeomSegment, : object 'rural' not found

(Uncomment the code and make the cell below markdown to see my solution.)

In [ ]:
# ![](https://github.com/chuckpr/BIOS512/blob/main/in-class-exercises/12/12_01_pivot_chart.png?raw=true)